// WARNING: This file is automatically generated from directoryTemplate.ts,
//          do NOT edit it manually!
import type { Processes } from "contexts/process/types";
// eslint-disable-next-line @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports
import dynamic from "next/dynamic";

const processDirectoryGenerated: Processes = {
  BoxedWine: {
    Component: dynamic(() => import("components/apps/BoxedWine/component")),
    allowResizing: false,
    background: "#000",
    defaultSize: {
      height: 480,
      width: 640,
    },
    icon: "/System/Icons/boxedwine.webp",
    singleton: true,
    title: "BoxedWine",
  },
};

export default processDirectoryGenerated;
